
import { SafetyItem } from './types';

export const SAFETY_ITEMS: SafetyItem[] = [
  // --- FOOD: DAIRY & PROTEIN ---
  { id: '1', name: 'Pasteurized Milk', category: 'Food', status: 'Safe', reason: 'Calcium is essential. Ensure it is pasteurized.' },
  { id: '2', name: 'Raw Milk', category: 'Food', status: 'Avoid', reason: 'High risk of Listeria, E.coli, and Salmonella.' },
  { id: '3', name: 'Curd / Dahi', category: 'Food', status: 'Safe', reason: 'Excellent probiotic and calcium source.' },
  { id: '4', name: 'Paneer (Cooked)', category: 'Food', status: 'Safe', reason: 'Safe protein source if made from pasteurized milk.' },
  { id: '5', name: 'Raw Paneer', category: 'Food', status: 'Caution', reason: 'Risk of contamination if not fresh. Better cooked.' },
  { id: '6', name: 'Cheese (Hard - Cheddar/Parmesan)', category: 'Food', status: 'Safe', reason: 'Low moisture prevents bacterial growth.' },
  { id: '7', name: 'Cheese (Soft - Brie/Camembert/Blue)', category: 'Food', status: 'Avoid', reason: 'Listeria risk unless cooked steaming hot.' },
  { id: '8', name: 'Ghee', category: 'Food', status: 'Safe', reason: 'Healthy fats. Good in moderation (1-2 tsp/day).' },
  { id: '9', name: 'Butter', category: 'Food', status: 'Safe', reason: 'Safe. Pasteurized salted/unsalted.' },
  { id: '10', name: 'Eggs (Fully Cooked/Hard Boiled)', category: 'Food', status: 'Safe', reason: 'Choline and Protein source.' },
  { id: '11', name: 'Eggs (Runny/Poached/Half-fry)', category: 'Food', status: 'Avoid', reason: 'Salmonella risk.' },
  { id: '12', name: 'Chicken (Fully Cooked)', category: 'Food', status: 'Safe', reason: 'Safe. No pink meat should remain.' },
  { id: '13', name: 'Mutton / Lamb', category: 'Food', status: 'Safe', reason: 'Iron source. Must be cooked thoroughly (pressure cooker).' },
  { id: '14', name: 'Liver (Kaleji)', category: 'Food', status: 'Avoid', reason: 'Very high Vitamin A (Retinol) - Teratogenic risk.' },
  { id: '15', name: 'Fish (Salmon/Ravas)', category: 'Food', status: 'Safe', reason: 'Low mercury, high Omega-3. Fully cooked only.' },
  { id: '16', name: 'Fish (Shark/Swordfish/King Mackerel)', category: 'Food', status: 'Avoid', reason: 'High Mercury content damages fetal brain.' },
  { id: '17', name: 'Fish (Tuna/Canned)', category: 'Food', status: 'Caution', reason: 'Limit to 1 serving/week due to mercury.' },
  { id: '18', name: 'Shrimp / Prawns', category: 'Food', status: 'Safe', reason: 'Safe if fully cooked.' },
  { id: '19', name: 'Crab', category: 'Food', status: 'Safe', reason: 'Safe cooked. Avoid the organs (hepatopancreas).' },
  { id: '20', name: 'Sushi / Sashimi', category: 'Food', status: 'Avoid', reason: 'Parasite and bacteria risk in raw fish.' },
  { id: '21', name: 'Tofu', category: 'Food', status: 'Safe', reason: 'Great plant protein.' },
  { id: '22', name: 'Soya Chunks', category: 'Food', status: 'Safe', reason: 'Good protein. Moderate intake.' },
  { id: '23', name: 'Protein Powder (Whey)', category: 'Food', status: 'Safe', reason: 'Safe if brand is reputable and sugar is low.' },
  { id: '24', name: 'Raw Sprouts', category: 'Food', status: 'Avoid', reason: 'Seeds harbor E.coli/Salmonella internally. Must cook.' },
  { id: '25', name: 'Cooked Sprouts', category: 'Food', status: 'Safe', reason: 'Safe and nutritious.' },

  // --- FOOD: GRAINS & MILLETS (INDIAN) ---
  { id: '26', name: 'Ragi (Finger Millet)', category: 'Food', status: 'Safe', reason: 'Excellent Calcium and Iron.' },
  { id: '27', name: 'Jowar (Sorghum)', category: 'Food', status: 'Safe', reason: 'High fiber, gluten-free.' },
  { id: '28', name: 'Bajra (Pearl Millet)', category: 'Food', status: 'Caution', reason: 'Heat-producing (garam taseer). Moderate in winter/T3.' },
  { id: '29', name: 'Oats', category: 'Food', status: 'Safe', reason: 'Great for constipation and energy.' },
  { id: '30', name: 'Quinoa', category: 'Food', status: 'Safe', reason: 'Complete protein.' },
  { id: '31', name: 'White Rice', category: 'Food', status: 'Safe', reason: 'Safe. Brown rice is healthier for GDM.' },
  { id: '32', name: 'Maida (Refined Flour)', category: 'Food', status: 'Caution', reason: 'Constipating and low nutrient value.' },
  { id: '33', name: 'Sabudana (Tapioca)', category: 'Food', status: 'Safe', reason: 'Safe carb source.' },
  { id: '34', name: 'Corn / Bhutta', category: 'Food', status: 'Safe', reason: 'Rich in folic acid.' },

  // --- FOOD: FRUITS ---
  { id: '35', name: 'Ripe Papaya', category: 'Food', status: 'Safe', reason: 'Rich in Vitamin A/C. Safe.' },
  { id: '36', name: 'Unripe/Semi-ripe Papaya', category: 'Food', status: 'Avoid', reason: 'Contains Latex which triggers uterine contractions.' },
  { id: '37', name: 'Pineapple', category: 'Food', status: 'Caution', reason: 'Contains Bromelain. Small amounts safe; excess causes softening of cervix.' },
  { id: '38', name: 'Grapes', category: 'Food', status: 'Caution', reason: 'Resveratrol in skin is debated. Pesticide risk (wash well).' },
  { id: '39', name: 'Banana', category: 'Food', status: 'Safe', reason: 'Potassium helps leg cramps.' },
  { id: '40', name: 'Apple', category: 'Food', status: 'Safe', reason: 'High fiber.' },
  { id: '41', name: 'Pomegranate (Anar)', category: 'Food', status: 'Safe', reason: 'Excellent for Iron/Hemoglobin.' },
  { id: '42', name: 'Guava', category: 'Food', status: 'Safe', reason: 'Low glycemic, high Vitamin C.' },
  { id: '43', name: 'Mango', category: 'Food', status: 'Safe', reason: 'Safe in moderation (High sugar - watch GDM).' },
  { id: '44', name: 'Litchi', category: 'Food', status: 'Caution', reason: 'High sugar ("heaty"). Limit intake.' },
  { id: '45', name: 'Custard Apple (Sitaphal)', category: 'Food', status: 'Safe', reason: 'Good energy source. Watch sugar.' },
  { id: '46', name: 'Jackfruit (Ripe)', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '47', name: 'Jackfruit (Raw/Kathal)', category: 'Food', status: 'Safe', reason: 'Good vegetable alternative. Cook well.' },
  { id: '48', name: 'Jamun', category: 'Food', status: 'Safe', reason: 'Good for regulating blood sugar.' },
  { id: '49', name: 'Watermelon', category: 'Food', status: 'Safe', reason: 'Hydrating and helps with swelling.' },
  { id: '50', name: 'Coconut Water', category: 'Food', status: 'Safe', reason: 'Best natural electrolyte source.' },
  { id: '51', name: 'Sugarcane Juice', category: 'Food', status: 'Caution', reason: 'Hygiene risk (Jaundice/Typhoid) if street bought.' },
  { id: '52', name: 'Dates (Khajoor)', category: 'Food', status: 'Safe', reason: 'Iron rich. 2-4/day is beneficial.' },
  { id: '53', name: 'Dry Figs (Anjeer)', category: 'Food', status: 'Safe', reason: 'Help with constipation.' },

  // --- FOOD: VEGETABLES ---
  { id: '54', name: 'Spinach (Palak)', category: 'Food', status: 'Safe', reason: 'Wash thoroughly. Folic acid rich.' },
  { id: '55', name: 'Fenugreek Leaves (Methi)', category: 'Food', status: 'Safe', reason: 'Iron rich.' },
  { id: '56', name: 'Brinjal / Eggplant', category: 'Food', status: 'Safe', reason: 'Safe. Myth about it being "harmful" is unfounded.' },
  { id: '57', name: 'Bitter Gourd (Karela)', category: 'Food', status: 'Caution', reason: 'Excess can lower sugar too much or stimulate uterus.' },
  { id: '58', name: 'Bottle Gourd (Lauki)', category: 'Food', status: 'Safe', reason: 'Hydrating and safe.' },
  { id: '59', name: 'Drumstick (Moringa)', category: 'Food', status: 'Safe', reason: 'Superfood for Calcium/Iron.' },
  { id: '60', name: 'Aloe Vera Juice', category: 'Food', status: 'Avoid', reason: 'Cathartic agent. Can cause uterine contractions.' },
  { id: '61', name: 'Bamboo Shoots', category: 'Food', status: 'Caution', reason: 'Must be cooked properly to remove toxins.' },
  { id: '62', name: 'Mushrooms', category: 'Food', status: 'Safe', reason: 'Safe if cooked. Avoid wild mushrooms.' },

  // --- FOOD: SPICES & HERBS ---
  { id: '63', name: 'Turmeric (Haldi)', category: 'Food', status: 'Safe', reason: 'Anti-inflammatory. Safe in food amounts.' },
  { id: '64', name: 'Ginger', category: 'Food', status: 'Safe', reason: 'Good for nausea. Safe in food.' },
  { id: '65', name: 'Garlic', category: 'Food', status: 'Safe', reason: 'Immunity booster.' },
  { id: '66', name: 'Saffron (Kesar)', category: 'Food', status: 'Caution', reason: 'Few strands in milk is safe. Excess causes contractions.' },
  { id: '67', name: 'Fennel Seeds (Saunf)', category: 'Food', status: 'Safe', reason: 'Digestion aid. Safe.' },
  { id: '68', name: 'Cumin (Jeera)', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '69', name: 'Fenugreek Seeds (Methi Dana)', category: 'Food', status: 'Caution', reason: 'High doses (medicinal) can stimulate uterus. Food tempering is safe.' },
  { id: '70', name: 'Asafoetida (Hing)', category: 'Food', status: 'Safe', reason: 'Safe in cooking amounts.' },
  { id: '71', name: 'Tulsi (Holy Basil)', category: 'Food', status: 'Caution', reason: 'Avoid medicinal concentrates. 1-2 leaves in tea is okay.' },
  { id: '72', name: 'Sesame Seeds (Til)', category: 'Food', status: 'Caution', reason: 'T1 avoid excess. T2/T3 moderate is fine. High heat property.' },
  { id: '73', name: 'Ajwain (Carom Seeds)', category: 'Food', status: 'Safe', reason: 'Good for gas/bloating.' },
  { id: '74', name: 'Cinnamon', category: 'Food', status: 'Safe', reason: 'Flavoring is safe. Avoid supplements.' },
  { id: '75', name: 'Nutmeg (Jaiphal)', category: 'Food', status: 'Caution', reason: 'Use pinch only. High dose is toxic.' },
  { id: '76', name: 'Star Anise', category: 'Food', status: 'Safe', reason: 'Safe in food.' },
  { id: '77', name: 'Curry Leaves', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '78', name: 'Mint (Pudina)', category: 'Food', status: 'Safe', reason: 'Helps nausea.' },

  // --- FOOD: INDIAN STREET FOOD & DISHES ---
  { id: '79', name: 'Pani Puri / Golgappa', category: 'Food', status: 'Caution', reason: 'High risk of water-borne infection (Typhoid/Jaundice).' },
  { id: '80', name: 'Samosa / Fried Snacks', category: 'Food', status: 'Caution', reason: 'Acidity and heartburn risk.' },
  { id: '81', name: 'Idli / Dosa', category: 'Food', status: 'Safe', reason: 'Fermented and steamed. Very safe.' },
  { id: '82', name: 'Dhokla', category: 'Food', status: 'Safe', reason: 'Steamed and safe.' },
  { id: '83', name: 'Chinese (Roadside)', category: 'Food', status: 'Avoid', reason: 'Hygiene risk and likely high MSG/Sodium.' },
  { id: '84', name: 'Momos (Steamed)', category: 'Food', status: 'Caution', reason: 'Ensure filling (cabbage/meat) is fully cooked.' },
  { id: '85', name: 'Bhel Puri', category: 'Food', status: 'Caution', reason: 'Safe if chutneys are fresh/hygienic.' },
  { id: '86', name: 'Chaat (Dahi Puri)', category: 'Food', status: 'Caution', reason: 'Yogurt must be fresh. Hygiene is key.' },
  { id: '87', name: 'Vada Pav', category: 'Food', status: 'Caution', reason: 'Acidity trigger.' },
  { id: '88', name: 'Pav Bhaji', category: 'Food', status: 'Safe', reason: 'If homemade or hygienic. Good veggie mix.' },
  { id: '89', name: 'Pickles (Achar)', category: 'Food', status: 'Caution', reason: 'Very high salt/oil. Edema/Heartburn risk.' },
  { id: '90', name: 'Papad', category: 'Food', status: 'Caution', reason: 'High sodium.' },

  // --- BEVERAGES ---
  { id: '91', name: 'Masala Chai', category: 'Food', status: 'Caution', reason: 'Caffeine content. Limit to 2 small cups.' },
  { id: '92', name: 'Filter Coffee', category: 'Food', status: 'Caution', reason: 'Higher caffeine than instant. Limit to 1 cup.' },
  { id: '93', name: 'Green Tea', category: 'Food', status: 'Caution', reason: 'EGCG can inhibit folic acid. Limit to 1-2 cups.' },
  { id: '94', name: 'Alcohol', category: 'Food', status: 'Avoid', reason: 'Fetal Alcohol Syndrome. No safe limit.' },
  { id: '95', name: 'Buttermilk (Chaas)', category: 'Food', status: 'Safe', reason: 'Cooling and digestive.' },
  { id: '96', name: 'Lassi', category: 'Food', status: 'Safe', reason: 'Good calcium/protein.' },
  { id: '97', name: 'Thandai', category: 'Food', status: 'Safe', reason: 'Without Bhang (Cannabis). High calorie.' },
  { id: '98', name: 'Rooh Afza', category: 'Food', status: 'Caution', reason: 'High sugar.' },
  { id: '99', name: 'Soda / Aerated Drinks', category: 'Food', status: 'Avoid', reason: 'Zero nutrition, high sugar/caffeine.' },
  { id: '100', name: 'Energy Drinks (Red Bull)', category: 'Food', status: 'Avoid', reason: 'High caffeine and stimulants.' },
  { id: '101', name: 'Kombucha', category: 'Food', status: 'Avoid', reason: 'Unpasteurized and traces of alcohol.' },
  { id: '102', name: 'Jaljeera', category: 'Food', status: 'Safe', reason: 'Good for digestion.' },
  { id: '103', name: 'Sol Kadhi', category: 'Food', status: 'Safe', reason: 'Excellent digestive (Kokum + Coconut milk).' },

  // --- ACTIVITY: EXERCISE & MOVEMENT ---
  { id: '104', name: 'Walking', category: 'Activity', status: 'Safe', reason: 'Best exercise. 30 mins daily recommended.' },
  { id: '105', name: 'Squatting (Indian Toilet)', category: 'Activity', status: 'Safe', reason: 'Good for pelvic floor unless cervical incompetence.' },
  { id: '106', name: 'Prenatal Yoga', category: 'Activity', status: 'Safe', reason: 'Excellent under guidance.' },
  { id: '107', name: 'Surya Namaskar', category: 'Activity', status: 'Caution', reason: 'Modify poses. Avoid lying on belly.' },
  { id: '108', name: 'Kapalbhati (Pranayam)', category: 'Activity', status: 'Avoid', reason: 'Forceful abdominal contractions are dangerous.' },
  { id: '109', name: 'Anulom Vilom', category: 'Activity', status: 'Safe', reason: 'Safe and relaxing.' },
  { id: '110', name: 'Swimming', category: 'Activity', status: 'Safe', reason: 'Relieves joint pain.' },
  { id: '111', name: 'Zumba', category: 'Activity', status: 'Caution', reason: 'Low impact only. Avoid jumping/twisting.' },
  { id: '112', name: 'Planks', category: 'Activity', status: 'Caution', reason: 'Avoid if Diastasis Recti (ab separation) occurs.' },
  { id: '113', name: 'Crunches', category: 'Activity', status: 'Avoid', reason: 'Strain on abdomen and back.' },
  { id: '114', name: 'Heavy Lifting (>10kg)', category: 'Activity', status: 'Avoid', reason: 'Strain on back and pelvic floor.' },
  { id: '115', name: 'Climbing Stairs', category: 'Activity', status: 'Safe', reason: 'Safe unless balance issues or doctor advised bedrest.' },
  { id: '116', name: 'Bending Forward', category: 'Activity', status: 'Caution', reason: 'Squat instead of bending from waist.' },
  { id: '117', name: 'Sleeping on Back', category: 'Activity', status: 'Avoid', reason: 'After 20 weeks, compresses Vena Cava (blood flow).' },
  { id: '118', name: 'Sleeping on Left Side', category: 'Activity', status: 'Safe', reason: 'Best for placental blood flow.' },
  { id: '119', name: 'Kegel Exercises', category: 'Activity', status: 'Safe', reason: 'Strengthens pelvic floor.' },
  { id: '120', name: 'Butterfly Pose', category: 'Activity', status: 'Safe', reason: 'Good for hip opening.' },
  { id: '121', name: 'High Intensity Interval Training (HIIT)', category: 'Activity', status: 'Avoid', reason: 'Keep heart rate moderate.' },
  { id: '122', name: 'Cycling', category: 'Activity', status: 'Caution', reason: 'Balance issues. Stationary bike is safer.' },
  { id: '123', name: 'Horse Riding', category: 'Activity', status: 'Avoid', reason: 'Fall risk.' },
  { id: '124', name: 'Amusement Park Rides', category: 'Activity', status: 'Avoid', reason: 'Jerky movements and G-force.' },
  { id: '125', name: 'Hot Yoga / Bikram', category: 'Activity', status: 'Avoid', reason: 'Overheating risk.' },

  // --- ACTIVITY: TRAVEL & LIFESTYLE ---
  { id: '126', name: 'Driving Car', category: 'Activity', status: 'Safe', reason: 'Wear seatbelt below the bump.' },
  { id: '127', name: 'Two-Wheeler (Scooty/Bike)', category: 'Activity', status: 'Caution', reason: 'Balance risk and bumpy roads. Avoid in T3.' },
  { id: '128', name: 'Auto Rickshaw', category: 'Activity', status: 'Caution', reason: 'Very bumpy. Hold support.' },
  { id: '129', name: 'Air Travel', category: 'Activity', status: 'Safe', reason: 'Safe until 36 weeks. Walk every hour.' },
  { id: '130', name: 'Train Travel', category: 'Activity', status: 'Caution', reason: 'Hygiene and crowd risk. Carry own food/water.' },
  { id: '131', name: 'Sexual Intercourse', category: 'Activity', status: 'Safe', reason: 'Safe unless Placenta Previa/Bleeding/Cervical issues.' },
  { id: '132', name: 'Hair Dye', category: 'Beauty', status: 'Caution', reason: 'Wait till T2. Use Ammonia-free.' },
  { id: '133', name: 'Henna (Mehendi) on Hands', category: 'Beauty', status: 'Safe', reason: 'Natural henna is safe.' },
  { id: '134', name: 'Black Henna (Hair)', category: 'Beauty', status: 'Avoid', reason: 'Contains PPD (chemical). Avoid.' },
  { id: '135', name: 'Manicure / Pedicure', category: 'Beauty', status: 'Safe', reason: 'Ensure sterilized tools.' },
  { id: '136', name: 'Prenatal Massage', category: 'Beauty', status: 'Safe', reason: 'By trained therapist. No pressure on belly.' },
  { id: '137', name: 'Waxing', category: 'Beauty', status: 'Safe', reason: 'Skin is more sensitive.' },
  { id: '138', name: 'Laser Hair Removal', category: 'Beauty', status: 'Avoid', reason: 'Postpone until after delivery.' },
  { id: '139', name: 'Sauna / Steam Bath', category: 'Beauty', status: 'Avoid', reason: 'Hyperthermia risk.' },
  { id: '140', name: 'Hot Water Bath', category: 'Beauty', status: 'Caution', reason: 'Warm is fine. Hot (>39°C) is dangerous.' },
  { id: '141', name: 'Wearing Heels', category: 'Activity', status: 'Caution', reason: 'Fall risk due to shifted center of gravity.' },
  { id: '142', name: 'Tight Clothing', category: 'Activity', status: 'Caution', reason: 'Restrictive blood flow. Wear loose cotton.' },

  // --- HOUSEHOLD & CHORES ---
  { id: '143', name: 'Sweeping/Mopping (Jhadu Pocha)', category: 'Household', status: 'Caution', reason: 'Bending/Squatting is okay if comfortable. Avoid if back pain.' },
  { id: '144', name: 'Washing Clothes (Hand)', category: 'Household', status: 'Caution', reason: 'Heavy lifting of wet clothes is bad for back.' },
  { id: '145', name: 'Cooking', category: 'Household', status: 'Safe', reason: 'Ensure ventilation. Take sitting breaks.' },
  { id: '146', name: 'Lifting Buckets', category: 'Household', status: 'Avoid', reason: 'Strain on uterus and back.' },
  { id: '147', name: 'Changing Cat Litter', category: 'Household', status: 'Avoid', reason: 'Toxoplasmosis risk.' },
  { id: '148', name: 'Gardening', category: 'Household', status: 'Safe', reason: 'Wear gloves (Toxoplasmosis in soil).' },
  { id: '149', name: 'Using Microwave', category: 'Household', status: 'Safe', reason: 'No radiation leak.' },
  { id: '150', name: 'Mosquito Coils', category: 'Household', status: 'Avoid', reason: 'Smoke is harmful. Use nets or safe repellents.' },
  { id: '151', name: 'Liquid Vaporizers (All Out)', category: 'Household', status: 'Caution', reason: 'Chemical inhalation. Use in ventilated room.' },
  { id: '152', name: 'Incense Sticks (Agarbatti)', category: 'Household', status: 'Caution', reason: 'Smoke can irritate lungs.' },
  { id: '153', name: 'Camphor (Kapoor)', category: 'Household', status: 'Avoid', reason: 'Inhalation/ingestion is toxic to fetus.' },
  { id: '154', name: 'Floor Cleaners (Lizol/Phenyl)', category: 'Household', status: 'Caution', reason: 'Avoid direct contact/fumes.' },
  { id: '155', name: 'Paint Fumes', category: 'Household', status: 'Avoid', reason: 'Lead or VOCs.' },
  { id: '156', name: 'Pesticides / Hit Spray', category: 'Household', status: 'Avoid', reason: 'Neurotoxins.' },
  { id: '157', name: 'Bathroom Acid', category: 'Household', status: 'Avoid', reason: 'Toxic fumes.' },

  // --- BEAUTY INGREDIENTS (SKINCARE) ---
  { id: '158', name: 'Retinol / Retinoids', category: 'Beauty', status: 'Avoid', reason: 'Vitamin A toxicity. Birth defects.' },
  { id: '159', name: 'Salicylic Acid (>2%)', category: 'Beauty', status: 'Avoid', reason: 'High absorption risk.' },
  { id: '160', name: 'Salicylic Acid (<2% / Face Wash)', category: 'Beauty', status: 'Safe', reason: 'Safe in low wash-off doses.' },
  { id: '161', name: 'Glycolic Acid', category: 'Beauty', status: 'Safe', reason: 'Safe < 10%.' },
  { id: '162', name: 'Lactic Acid', category: 'Beauty', status: 'Safe', reason: 'Safe.' },
  { id: '163', name: 'Vitamin C Serum', category: 'Beauty', status: 'Safe', reason: 'Great for Melasma/Pigmentation.' },
  { id: '164', name: 'Niacinamide', category: 'Beauty', status: 'Safe', reason: 'Safe for acne.' },
  { id: '165', name: 'Hyaluronic Acid', category: 'Beauty', status: 'Safe', reason: 'Safe moisturizer.' },
  { id: '166', name: 'Benzoyl Peroxide', category: 'Beauty', status: 'Safe', reason: 'Safe in low amounts for spot treatment.' },
  { id: '167', name: 'Hydroquinone', category: 'Beauty', status: 'Avoid', reason: 'High absorption rate. Unsafe.' },
  { id: '168', name: 'Azelaic Acid', category: 'Beauty', status: 'Safe', reason: 'Safest acne treatment in pregnancy.' },
  { id: '169', name: 'Sunscreen (Physical/Mineral)', category: 'Beauty', status: 'Safe', reason: 'Zinc Oxide/Titanium Dioxide are best.' },
  { id: '170', name: 'Chemical Sunscreen (Oxybenzone)', category: 'Beauty', status: 'Caution', reason: 'Endocrine disruptor. Prefer mineral.' },
  { id: '171', name: 'Essential Oils (Pure)', category: 'Beauty', status: 'Caution', reason: 'Must be diluted. Avoid Sage, Rosemary.' },
  { id: '172', name: 'Sheet Masks', category: 'Beauty', status: 'Safe', reason: 'Safe.' },
  { id: '173', name: 'Lipstick', category: 'Beauty', status: 'Safe', reason: 'Safe (minute ingestion).' },
  { id: '174', name: 'Botox / Fillers', category: 'Beauty', status: 'Avoid', reason: 'Not tested in pregnancy.' },
  { id: '175', name: 'Hair Rebonding / Keratin', category: 'Beauty', status: 'Avoid', reason: 'Formaldehyde fumes.' },

  // --- MEDICINES & HEALTH (OTC) ---
  { id: '176', name: 'Paracetamol / Crocin / Dolo', category: 'Household', status: 'Safe', reason: 'First line for pain/fever.' },
  { id: '177', name: 'Ibuprofen / Combiflam', category: 'Household', status: 'Avoid', reason: 'NSAID. Affects fetal kidneys/heart.' },
  { id: '178', name: 'Aspirin (High Dose)', category: 'Household', status: 'Avoid', reason: 'Bleeding risk.' },
  { id: '179', name: 'Aspirin (Low Dose 75/150mg)', category: 'Household', status: 'Safe', reason: 'ONLY if prescribed for Preeclampsia prevention.' },
  { id: '180', name: 'Diclofenac / Voveran', category: 'Household', status: 'Avoid', reason: 'NSAID. Unsafe.' },
  { id: '181', name: 'Vicks Vaporub', category: 'Household', status: 'Safe', reason: 'Safe for topical use.' },
  { id: '182', name: 'Iodex / Moov / Volini', category: 'Household', status: 'Caution', reason: 'Contain NSAIDs/Salicylates. Use sparingly. Avoid in T3.' },
  { id: '183', name: 'Antacids (Digene/Gelusil)', category: 'Household', status: 'Safe', reason: 'Safe for heartburn.' },
  { id: '184', name: 'Eno', category: 'Household', status: 'Caution', reason: 'High sodium. Avoid if you have BP issues.' },
  { id: '185', name: 'Pantoprazole / Omeprazole', category: 'Household', status: 'Safe', reason: 'Safe for acidity.' },
  { id: '186', name: 'Cetirizine (Cetzine)', category: 'Household', status: 'Safe', reason: 'Safe for allergy.' },
  { id: '187', name: 'Cough Syrup (Benadryl)', category: 'Household', status: 'Caution', reason: 'Avoid alcohol-based. Check ingredients.' },
  { id: '188', name: 'Cough Syrup (Ayurvedic)', category: 'Household', status: 'Caution', reason: 'Check for heavy metals/alcohol.' },
  { id: '189', name: 'Vitamins (A)', category: 'Household', status: 'Avoid', reason: 'High dose Retinol is teratogenic.' },
  { id: '190', name: 'Vitamins (Prenatal)', category: 'Household', status: 'Safe', reason: 'Necessary.' },
  { id: '191', name: 'Isabgol (Psyllium Husk)', category: 'Household', status: 'Safe', reason: 'Safe for constipation.' },
  { id: '192', name: 'Castor Oil', category: 'Household', status: 'Avoid', reason: 'Induces contractions/diarrhea.' },
  { id: '193', name: 'Gripe Water (for Mom)', category: 'Household', status: 'Safe', reason: 'Usually fennel/dill based. Safe.' },
  { id: '194', name: 'Hajmola', category: 'Household', status: 'Caution', reason: 'High salt.' },
  { id: '195', name: 'ORS (Electral)', category: 'Household', status: 'Safe', reason: 'Safe for dehydration.' },
  { id: '196', name: 'Glucose Powder', category: 'Household', status: 'Caution', reason: 'Raises sugar rapidly. Avoid in GDM.' },

  // --- TRADITIONAL / AYURVEDIC ---
  { id: '197', name: 'Chyawanprash', category: 'Food', status: 'Safe', reason: 'Immunity booster. Watch sugar.' },
  { id: '198', name: 'Shilajit', category: 'Food', status: 'Avoid', reason: 'Heating and unknown purity.' },
  { id: '199', name: 'Ashwagandha', category: 'Food', status: 'Caution', reason: 'Traditionally used, but large doses may cause miscarriage. Consult Vaidya.' },
  { id: '200', name: 'Shatavari', category: 'Food', status: 'Safe', reason: 'Good for lactation later. Safe in pregnancy.' },
  { id: '201', name: 'Triphala', category: 'Household', status: 'Caution', reason: 'Strong laxative. Use with care.' },
  { id: '202', name: 'Neem (Internal)', category: 'Food', status: 'Avoid', reason: 'Can interact with immune system/pregnancy.' },
  { id: '203', name: 'Karela Juice', category: 'Food', status: 'Caution', reason: 'Can lower sugar drastically.' },
  { id: '204', name: 'Gond Ladoo (Edible Gum)', category: 'Food', status: 'Caution', reason: 'Very heating/calorie dense. Best for Postpartum.' },
  { id: '205', name: 'Pan / Betel Leaf', category: 'Food', status: 'Avoid', reason: 'Stimulant. Often has areca nut (unsafe).' },
  { id: '206', name: 'Supari (Areca Nut)', category: 'Food', status: 'Avoid', reason: 'Carcinogenic and harmful.' },
  { id: '207', name: 'Mukhwas', category: 'Food', status: 'Safe', reason: 'If simple seeds (fennel/sesame). Avoid colored sweet ones.' },

  // --- MISC ADDITIONS TO REACH TARGET ---
  { id: '208', name: 'Sleeping Pills', category: 'Household', status: 'Avoid', reason: 'Consult doctor.' },
  { id: '209', name: 'Melatonin', category: 'Household', status: 'Caution', reason: 'Not enough data.' },
  { id: '210', name: 'X-Rays', category: 'Activity', status: 'Avoid', reason: 'Radiation risk (unless emergency).' },
  { id: '211', name: 'MRI', category: 'Activity', status: 'Safe', reason: 'Generally safe (no radiation). Avoid Gadolinium contrast.' },
  { id: '212', name: 'Ultrasound', category: 'Activity', status: 'Safe', reason: 'Sound waves. Safe.' },
  { id: '213', name: 'Dental X-Ray', category: 'Activity', status: 'Safe', reason: 'With lead apron shielding.' },
  { id: '214', name: 'Root Canal', category: 'Activity', status: 'Safe', reason: 'Safe with local anesthesia.' },
  { id: '215', name: 'Lidocaine (Local Anesthesia)', category: 'Household', status: 'Safe', reason: 'Safe.' },
  { id: '216', name: 'General Anesthesia', category: 'Activity', status: 'Caution', reason: 'Avoid unless emergency surgery.' },
  { id: '217', name: 'Tattooing', category: 'Beauty', status: 'Avoid', reason: 'Infection risk (Hepatitis/HIV) from needles.' },
  { id: '218', name: 'Piercing', category: 'Beauty', status: 'Caution', reason: 'Infection risk and slow healing.' },
  { id: '219', name: 'Contact Lenses', category: 'Beauty', status: 'Safe', reason: 'Eyes may get dry, but safe.' },
  { id: '220', name: 'Eye Drops (Saline)', category: 'Household', status: 'Safe', reason: 'Safe.' },
  { id: '221', name: 'Laptop on Lap', category: 'Activity', status: 'Safe', reason: 'Heat is minimal, radiation is non-ionizing.' },
  { id: '222', name: 'Heating Pad', category: 'Household', status: 'Safe', reason: 'Safe for back/hips. Don\'t put on belly.' },
  { id: '223', name: 'Electric Blanket', category: 'Household', status: 'Avoid', reason: 'Overheating risk.' },
  { id: '224', name: 'Hair Spray', category: 'Beauty', status: 'Caution', reason: 'Use in ventilated area.' },
  { id: '225', name: 'Nail Polish', category: 'Beauty', status: 'Safe', reason: 'Use 3-free or 5-free brands.' },
  { id: '226', name: 'Nail Polish Remover (Acetone)', category: 'Beauty', status: 'Safe', reason: 'Occasional use is safe.' },
  { id: '227', name: 'Whitening Strips (Teeth)', category: 'Beauty', status: 'Safe', reason: 'Safe.' },
  { id: '228', name: 'Charcoal Toothpaste', category: 'Beauty', status: 'Safe', reason: 'Safe.' },
  { id: '229', name: 'Mouthwash (Alcohol-free)', category: 'Beauty', status: 'Safe', reason: 'Safe.' },
  { id: '230', name: 'Probiotics', category: 'Household', status: 'Safe', reason: 'Beneficial.' },
  { id: '231', name: 'Fish Oil Supplements', category: 'Household', status: 'Safe', reason: 'Good source of DHA. Ensure mercury-free.' },
  { id: '232', name: 'Evening Primrose Oil (Oral)', category: 'Household', status: 'Caution', reason: 'Used to ripen cervix in late term. Don\'t take early.' },
  { id: '233', name: 'Black Cohosh', category: 'Household', status: 'Avoid', reason: 'Induces labor.' },
  { id: '234', name: 'Blue Cohosh', category: 'Household', status: 'Avoid', reason: 'Toxic to fetal heart.' },
  { id: '235', name: 'Raspberry Leaf Tea', category: 'Food', status: 'Caution', reason: 'T3 only. Tones uterus.' },
  { id: '236', name: 'Peppermint Tea', category: 'Food', status: 'Safe', reason: 'Safe for nausea.' },
  { id: '237', name: 'Chamomile Tea', category: 'Food', status: 'Safe', reason: 'Safe for sleep.' },
  { id: '238', name: 'Hibiscus Tea', category: 'Food', status: 'Caution', reason: 'Some evidence of hormonal effect. Limit.' },
  { id: '239', name: 'Lemongrass', category: 'Food', status: 'Safe', reason: 'Safe in food.' },
  { id: '240', name: 'Oregano Oil (Concentrated)', category: 'Household', status: 'Avoid', reason: 'Uterine stimulant.' },
  { id: '241', name: 'Oregano (Herb)', category: 'Food', status: 'Safe', reason: 'Safe in pizza/pasta.' },
  { id: '242', name: 'Basil (Herb)', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '243', name: 'Rosemary (Herb)', category: 'Food', status: 'Safe', reason: 'Safe in food.' },
  { id: '244', name: 'Parsley (Herb)', category: 'Food', status: 'Safe', reason: 'Safe in food. Avoid oil/concentrates.' },
  { id: '245', name: 'Wasabi', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '246', name: 'Vinegar', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '247', name: 'Apple Cider Vinegar', category: 'Food', status: 'Safe', reason: 'Safe (Pasteurized preferred).' },
  { id: '248', name: 'Honey', category: 'Food', status: 'Safe', reason: 'Safe for adults (Botulism risk is for infants).' },
  { id: '249', name: 'Maple Syrup', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '250', name: 'Agave Nectar', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '251', name: 'Stevia', category: 'Food', status: 'Safe', reason: 'Safe natural sweetener.' },
  { id: '252', name: 'Aspartame (Equal)', category: 'Food', status: 'Safe', reason: 'Safe in moderation.' },
  { id: '253', name: 'Sucralose (Splenda)', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '254', name: 'Saccharin', category: 'Food', status: 'Avoid', reason: 'Crosses placenta. Better options available.' },
  { id: '255', name: 'Maggi / Noodles', category: 'Food', status: 'Caution', reason: 'Refined flour and high sodium/preservatives.' },
  { id: '256', name: 'Pasta', category: 'Food', status: 'Safe', reason: 'Safe. Whole wheat is better.' },
  { id: '257', name: 'Bread', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '258', name: 'Pizza', category: 'Food', status: 'Safe', reason: 'Safe if toppings cooked and cheese pasteurized.' },
  { id: '259', name: 'Burger', category: 'Food', status: 'Safe', reason: 'Safe if patty fully cooked.' },
  { id: '260', name: 'Hot Dogs', category: 'Food', status: 'Caution', reason: 'Listeria risk. Cook till steaming.' },
  { id: '261', name: 'Pepperoni', category: 'Food', status: 'Caution', reason: 'Preservatives/Nitrates + Listeria risk. Cook well.' },
  { id: '262', name: 'Bacon', category: 'Food', status: 'Safe', reason: 'Safe if cooked crispy.' },
  { id: '263', name: 'Ham', category: 'Food', status: 'Caution', reason: 'High sodium + Listeria risk.' },
  { id: '264', name: 'Sausages', category: 'Food', status: 'Safe', reason: 'Cook thoroughly.' },
  { id: '265', name: 'Salami', category: 'Food', status: 'Caution', reason: 'Cured meat. Cook before eating.' },
  { id: '266', name: 'Prosciutto', category: 'Food', status: 'Avoid', reason: 'Uncooked cured meat.' },
  { id: '267', name: 'Chorizo', category: 'Food', status: 'Safe', reason: 'If cooked.' },
  { id: '268', name: 'Gelatin', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '269', name: 'Marshmallows', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '270', name: 'Chewing Gum', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '271', name: 'Mint Sweets', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '272', name: 'Dark Chocolate', category: 'Food', status: 'Safe', reason: 'Antioxidants. Good in moderation.' },
  { id: '273', name: 'White Chocolate', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '274', name: 'Nutella', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '275', name: 'Peanut Chikki', category: 'Food', status: 'Safe', reason: 'Good protein/iron.' },
  { id: '276', name: 'Cashews (Kaju)', category: 'Food', status: 'Safe', reason: 'Good fats.' },
  { id: '277', name: 'Pistachios', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '278', name: 'Raisins (Kishmish)', category: 'Food', status: 'Safe', reason: 'Iron/Fiber.' },
  { id: '279', name: 'Apricots (Khubani)', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '280', name: 'Prunes', category: 'Food', status: 'Safe', reason: 'Excellent for constipation.' },
  { id: '281', name: 'Cranberries', category: 'Food', status: 'Safe', reason: 'Good for UTI prevention.' },
  { id: '282', name: 'Blueberries', category: 'Food', status: 'Safe', reason: 'Antioxidants.' },
  { id: '283', name: 'Strawberries', category: 'Food', status: 'Safe', reason: 'Wash well.' },
  { id: '284', name: 'Kiwi', category: 'Food', status: 'Safe', reason: 'Vitamin C and Folate.' },
  { id: '285', name: 'Avocado', category: 'Food', status: 'Safe', reason: 'Healthy fats/Folate.' },
  { id: '286', name: 'Olives', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '287', name: 'Hummus', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '288', name: 'Tahini', category: 'Food', status: 'Safe', reason: 'Safe sesame paste.' },
  { id: '289', name: 'Pesto', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '290', name: 'Mustard', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '291', name: 'Ketchup', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '292', name: 'BBQ Sauce', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '293', name: 'Sriracha', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '294', name: 'Chili Flakes', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '295', name: 'Black Pepper', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '296', name: 'Saltwater Gargle', category: 'Household', status: 'Safe', reason: 'Safe for sore throat.' },
  { id: '297', name: 'Steam Inhalation', category: 'Household', status: 'Safe', reason: 'Safe for congestion.' },
  { id: '298', name: 'Neti Pot', category: 'Household', status: 'Safe', reason: 'Use sterile water.' },
  { id: '299', name: 'CPAP Machine', category: 'Household', status: 'Safe', reason: 'Safe for sleep apnea.' },
  { id: '300', name: 'Inhalers (Asthma)', category: 'Household', status: 'Safe', reason: 'Vital to breathe. Continue usage.' },
  
  // --- EXPANSION TO 500+ ---
  // More Specific Indian Foods
  { id: '301', name: 'Amla (Indian Gooseberry)', category: 'Food', status: 'Safe', reason: 'Highest Vitamin C. Good for immunity.' },
  { id: '302', name: 'Kokum', category: 'Food', status: 'Safe', reason: 'Cooling, helps acidity.' },
  { id: '303', name: 'Tamarind (Imli)', category: 'Food', status: 'Safe', reason: 'Safe in moderation. Excess causes acidity.' },
  { id: '304', name: 'Raw Mango (Kairi)', category: 'Food', status: 'Safe', reason: 'Good for nausea (Aam Panna).' },
  { id: '305', name: 'Singhara (Water Chestnut)', category: 'Food', status: 'Safe', reason: 'Nutritious.' },
  { id: '306', name: 'Lotus Stem (Kamal Kakdi)', category: 'Food', status: 'Safe', reason: 'Wash very well (muddy water). Cook thoroughly.' },
  { id: '307', name: 'Colocasia (Arbi)', category: 'Food', status: 'Safe', reason: 'Safe carb source.' },
  { id: '308', name: 'Yam (Suran)', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '309', name: 'Beetroot', category: 'Food', status: 'Safe', reason: 'Increases hemoglobin.' },
  { id: '310', name: 'Carrot', category: 'Food', status: 'Safe', reason: 'Vitamin A (Beta carotene).' },
  { id: '311', name: 'Radish (Mooli)', category: 'Food', status: 'Safe', reason: 'Safe cooked. Avoid raw if hygiene doubtful.' },
  { id: '312', name: 'Turnip (Shalgam)', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '313', name: 'Cabbage', category: 'Food', status: 'Caution', reason: 'Worm infestation risk. Cook very well. Avoid raw coleslaw.' },
  { id: '314', name: 'Cauliflower', category: 'Food', status: 'Safe', reason: 'Gas causing, but safe.' },
  { id: '315', name: 'Broccoli', category: 'Food', status: 'Safe', reason: 'Calcium/Folate rich.' },
  { id: '316', name: 'Capsicum / Bell Pepper', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '317', name: 'Green Chillies', category: 'Food', status: 'Safe', reason: 'Rich in Vit C. Causes heartburn.' },
  { id: '318', name: 'Red Chilli Powder', category: 'Food', status: 'Caution', reason: 'Acidity trigger.' },
  { id: '319', name: 'Garam Masala', category: 'Food', status: 'Safe', reason: 'Safe in moderation.' },
  { id: '320', name: 'Chaat Masala', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '321', name: 'Black Salt (Kala Namak)', category: 'Food', status: 'Safe', reason: 'Good for digestion.' },
  { id: '322', name: 'Rock Salt (Sendha Namak)', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '323', name: 'Poppy Seeds (Khus Khus)', category: 'Food', status: 'Safe', reason: 'Safe in food (Kheer/Curry). Avoid large amounts.' },
  { id: '324', name: 'Melon Seeds (Magaj)', category: 'Food', status: 'Safe', reason: 'Protein rich.' },
  { id: '325', name: 'Sunflower Seeds', category: 'Food', status: 'Safe', reason: 'Folate rich.' },
  { id: '326', name: 'Chia Seeds', category: 'Food', status: 'Safe', reason: 'Omega-3 rich.' },
  { id: '327', name: 'Flax Seeds (Alsi)', category: 'Food', status: 'Caution', reason: 'Contains phytoestrogens. Limit to 1 tsp/day.' },
  { id: '328', name: 'Pumpkin Seeds', category: 'Food', status: 'Safe', reason: 'Iron/Zinc rich.' },
  { id: '329', name: 'Hemp Seeds', category: 'Food', status: 'Safe', reason: 'Complete protein.' },
  { id: '330', name: 'Makhana (Fox Nuts)', category: 'Food', status: 'Safe', reason: 'Excellent snack. Calcium/Protein.' },
  { id: '331', name: 'Puffed Rice (Murmura)', category: 'Food', status: 'Safe', reason: 'Light snack.' },
  { id: '332', name: 'Beaten Rice (Poha)', category: 'Food', status: 'Safe', reason: 'Easy to digest.' },
  { id: '333', name: 'Vermicelli (Seviyan)', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '334', name: 'Daliya (Broken Wheat)', category: 'Food', status: 'Safe', reason: 'High fiber.' },
  { id: '335', name: 'Sooji / Rava', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '336', name: 'Besan (Chickpea Flour)', category: 'Food', status: 'Safe', reason: 'High protein.' },
  { id: '337', name: 'Sattu', category: 'Food', status: 'Safe', reason: 'Cooling drink, high protein.' },
  { id: '338', name: 'Rajma (Kidney Beans)', category: 'Food', status: 'Safe', reason: 'Protein. Gas causing.' },
  { id: '339', name: 'Chana (Chickpeas)', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '340', name: 'Moong Dal', category: 'Food', status: 'Safe', reason: 'Easiest dal to digest.' },
  { id: '341', name: 'Toor Dal', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '342', name: 'Urad Dal', category: 'Food', status: 'Safe', reason: 'Heavy to digest. Eat in moderation.' },
  { id: '343', name: 'Masoor Dal', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '344', name: 'Lobia (Black Eyed Peas)', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '345', name: 'Horse Gram (Kulthi)', category: 'Food', status: 'Caution', reason: 'Heat generating. Avoid in T1.' },
  
  // More Household & Activities
  { id: '346', name: 'Blowing Balloons', category: 'Activity', status: 'Safe', reason: 'Good lung exercise.' },
  { id: '347', name: 'Singing', category: 'Activity', status: 'Safe', reason: 'Relieves stress. Baby hears you.' },
  { id: '348', name: 'Dancing', category: 'Activity', status: 'Safe', reason: 'Safe if low impact/balance maintained.' },
  { id: '349', name: 'Knitting/Sewing', category: 'Activity', status: 'Safe', reason: 'Safe.' },
  { id: '350', name: 'Watching Horror Movies', category: 'Activity', status: 'Safe', reason: 'Adrenaline doesn\'t harm baby directly, but stress isn\'t great.' },
  { id: '351', name: 'Loud Music / Concerts', category: 'Activity', status: 'Caution', reason: 'Prolonged very loud noise can stress fetus.' },
  { id: '352', name: 'Wearing Seatbelt', category: 'Activity', status: 'Safe', reason: 'MANDATORY. Strap goes under the belly.' },
  { id: '353', name: 'Wearing Tight Jeans', category: 'Activity', status: 'Caution', reason: 'Uncomfortable. Use maternity jeans.' },
  { id: '354', name: 'Underwire Bra', category: 'Activity', status: 'Caution', reason: 'Can block milk ducts. Wireless is better.' },
  { id: '355', name: 'Synthetic Underwear', category: 'Activity', status: 'Avoid', reason: 'Risk of yeast infection. Wear cotton.' },
  { id: '356', name: 'Hair Straightening (Heat)', category: 'Beauty', status: 'Safe', reason: 'Safe.' },
  { id: '357', name: 'Hair Dryer', category: 'Beauty', status: 'Safe', reason: 'Safe.' },
  { id: '358', name: 'Bleaching Facial Hair', category: 'Beauty', status: 'Caution', reason: 'Chemical fumes. Avoid or use mild.' },
  { id: '359', name: 'Acrylic Nails', category: 'Beauty', status: 'Caution', reason: 'Fumes in salon. Ventilate.' },
  { id: '360', name: 'Using Laptop on Belly', category: 'Activity', status: 'Avoid', reason: 'Heat exposure directly on womb.' },
  
  // More Specific Foods (International/Modern)
  { id: '361', name: 'Acai Bowl', category: 'Food', status: 'Safe', reason: 'Safe unless unpasteurized juice used.' },
  { id: '362', name: 'Bubble Tea', category: 'Food', status: 'Caution', reason: 'Choking hazard (pearls) + High Caffeine/Sugar.' },
  { id: '363', name: 'Matcha', category: 'Food', status: 'Caution', reason: 'High Caffeine.' },
  { id: '364', name: 'Kimchi', category: 'Food', status: 'Safe', reason: 'Probiotic. Safe.' },
  { id: '365', name: 'Miso Soup', category: 'Food', status: 'Safe', reason: 'High sodium.' },
  { id: '366', name: 'Ramen (Instant)', category: 'Food', status: 'Caution', reason: 'High Sodium/MSG.' },
  { id: '367', name: 'Protein Bars', category: 'Food', status: 'Safe', reason: 'Check for excessive Vitamin A or herbal additives.' },
  { id: '368', name: 'Granola', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '369', name: 'Almond Milk', category: 'Food', status: 'Safe', reason: 'Safe calcium source.' },
  { id: '370', name: 'Soy Milk', category: 'Food', status: 'Safe', reason: 'Safe in moderation.' },
  { id: '371', name: 'Oat Milk', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '372', name: 'Rice Milk', category: 'Food', status: 'Safe', reason: 'Low protein, but safe.' },
  { id: '373', name: 'Goat Cheese', category: 'Food', status: 'Caution', reason: 'Often unpasteurized. Check label.' },
  { id: '374', name: 'Feta Cheese', category: 'Food', status: 'Caution', reason: 'Often unpasteurized. Check label.' },
  { id: '375', name: 'Mozzarella', category: 'Food', status: 'Safe', reason: 'Usually pasteurized. Safe.' },
  { id: '376', name: 'Ricotta', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '377', name: 'Cream Cheese', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '378', name: 'Sour Cream', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '379', name: 'Whipped Cream', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '380', name: 'Salad Dressing (Caesar)', category: 'Food', status: 'Caution', reason: 'Traditional uses raw egg. Commercial usually safe.' },
  { id: '381', name: 'Ranch Dressing', category: 'Food', status: 'Safe', reason: 'Commercial is safe.' },
  { id: '382', name: 'Vinaigrette', category: 'Food', status: 'Safe', reason: 'Safe.' },
  
  // More Meds & Chemicals
  { id: '383', name: 'Cough Drops (Halls/Strepsils)', category: 'Household', status: 'Safe', reason: 'Safe in moderation.' },
  { id: '384', name: 'Throat Lozenges', category: 'Household', status: 'Safe', reason: 'Safe.' },
  { id: '385', name: 'Antibiotics (Amoxicillin)', category: 'Household', status: 'Safe', reason: 'Safe if prescribed.' },
  { id: '386', name: 'Antibiotics (Doxycycline)', category: 'Household', status: 'Avoid', reason: 'Discolors baby teeth.' },
  { id: '387', name: 'Antifungal Cream', category: 'Household', status: 'Safe', reason: 'Clotrimazole is safe.' },
  { id: '388', name: 'Steroid Cream (Hydrocortisone)', category: 'Household', status: 'Safe', reason: 'Safe in small areas.' },
  { id: '389', name: 'Acne Cream (Retin-A)', category: 'Household', status: 'Avoid', reason: 'Vitamin A derivative.' },
  { id: '390', name: 'Sleeping Pills (Ambien)', category: 'Household', status: 'Caution', reason: 'Only if prescribed.' },
  { id: '391', name: 'Anti-Depressants (SSRI)', category: 'Household', status: 'Caution', reason: 'Risk/Benefit analysis needed. Do not stop abruptly.' },
  { id: '392', name: 'Insulin', category: 'Household', status: 'Safe', reason: 'Does not cross placenta. Safe for GDM.' },
  { id: '393', name: 'Metformin', category: 'Household', status: 'Safe', reason: 'Used for PCOS/Diabetes. Generally safe.' },
  { id: '394', name: 'Thyroxine', category: 'Household', status: 'Safe', reason: 'Essential for baby brain if you have Hypothyroid.' },
  { id: '395', name: 'Labetalol', category: 'Household', status: 'Safe', reason: 'Safe for BP.' },
  { id: '396', name: 'Methyldopa', category: 'Household', status: 'Safe', reason: 'Safe for BP.' },
  { id: '397', name: 'Amlodipine', category: 'Household', status: 'Caution', reason: 'Used if others fail.' },
  { id: '398', name: 'Telmisartan / Losartan', category: 'Household', status: 'Avoid', reason: 'Fetal renal damage.' },
  { id: '399', name: 'Enalapril / Ramipril', category: 'Household', status: 'Avoid', reason: 'Fetal renal damage.' },
  { id: '400', name: 'Warfarin', category: 'Household', status: 'Avoid', reason: 'Birth defects. Switch to Heparin.' },
  { id: '401', name: 'Heparin / LMWH', category: 'Household', status: 'Safe', reason: 'Does not cross placenta.' },
  { id: '402', name: 'Progesterone Supplements', category: 'Household', status: 'Safe', reason: 'Supports pregnancy.' },
  { id: '403', name: 'Dydrogesterone (Duphaston)', category: 'Household', status: 'Safe', reason: 'Safe.' },
  { id: '404', name: 'HCG Injections', category: 'Household', status: 'Safe', reason: 'Safe.' },
  { id: '405', name: 'Clomid / Letrozole', category: 'Household', status: 'Avoid', reason: 'Stop once pregnant.' },
  
  // Cleaners & Home
  { id: '406', name: 'Dish Soap', category: 'Household', status: 'Safe', reason: 'Safe.' },
  { id: '407', name: 'Laundry Detergent', category: 'Household', status: 'Safe', reason: 'Safe.' },
  { id: '408', name: 'Fabric Softener', category: 'Household', status: 'Safe', reason: 'Safe.' },
  { id: '409', name: 'Toilet Cleaner (Acid based)', category: 'Household', status: 'Caution', reason: 'Fumes. Ventilate well.' },
  { id: '410', name: 'Bleach', category: 'Household', status: 'Caution', reason: 'Wear gloves. Ventilate.' },
  { id: '411', name: 'Furniture Polish', category: 'Household', status: 'Caution', reason: 'Fumes.' },
  { id: '412', name: 'Shoe Polish', category: 'Household', status: 'Safe', reason: 'Safe.' },
  { id: '413', name: 'Super Glue', category: 'Household', status: 'Safe', reason: 'Safe.' },
  { id: '414', name: 'Air Freshener Spray', category: 'Household', status: 'Caution', reason: 'Artificial fragrances can nauseate.' },
  
  // Personal Care
  { id: '415', name: 'Deodorant / Antiperspirant', category: 'Beauty', status: 'Safe', reason: 'Aluminum is minimal absorption. Safe.' },
  { id: '416', name: 'Perfume', category: 'Beauty', status: 'Safe', reason: 'Safe. Some scents trigger nausea.' },
  { id: '417', name: 'Body Lotion', category: 'Beauty', status: 'Safe', reason: 'Safe.' },
  { id: '418', name: 'Face Wash', category: 'Beauty', status: 'Safe', reason: 'Safe.' },
  { id: '419', name: 'Shampoo / Conditioner', category: 'Beauty', status: 'Safe', reason: 'Safe.' },
  { id: '420', name: 'Soap', category: 'Beauty', status: 'Safe', reason: 'Safe.' },
  { id: '421', name: 'Hair Oil', category: 'Beauty', status: 'Safe', reason: 'Safe.' },
  { id: '422', name: 'Sanitary Pads', category: 'Beauty', status: 'Safe', reason: 'Safe (Postpartum lochia).' },
  { id: '423', name: 'Tampons', category: 'Beauty', status: 'Caution', reason: 'Avoid postpartum (Infection risk). Safe during period pre-pregnancy.' },
  { id: '424', name: 'Menstrual Cup', category: 'Beauty', status: 'Caution', reason: 'Avoid postpartum.' },
  { id: '425', name: 'Intimate Wash', category: 'Beauty', status: 'Caution', reason: 'Disrupts pH. Water is best.' },
  { id: '426', name: 'Douching', category: 'Beauty', status: 'Avoid', reason: 'Infection risk. Never douche.' },
  
  // Herbs & Ayurveda (More)
  { id: '427', name: 'Arjuna Bark', category: 'Food', status: 'Caution', reason: 'Cardiac herb. Consult doctor.' },
  { id: '428', name: 'Brahmi', category: 'Food', status: 'Safe', reason: 'Generally safe.' },
  { id: '429', name: 'Guggul', category: 'Food', status: 'Avoid', reason: 'Stimulates uterus.' },
  { id: '430', name: 'Manjistha', category: 'Food', status: 'Caution', reason: 'Blood purifier. Consult doctor.' },
  { id: '431', name: 'Mulethi (Licorice)', category: 'Food', status: 'Caution', reason: 'Raises BP. Avoid if hypertensive.' },
  { id: '432', name: 'Amla Candy', category: 'Food', status: 'Safe', reason: 'Good for nausea.' },
  { id: '433', name: 'Ginger Candy', category: 'Food', status: 'Safe', reason: 'Good for nausea.' },
  
  // Fruits/Veg Continuation
  { id: '434', name: 'Parsnip', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '435', name: 'Kale', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '436', name: 'Lettuce', category: 'Food', status: 'Safe', reason: 'Wash well.' },
  { id: '437', name: 'Celery', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '438', name: 'Zucchini', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '439', name: 'Asparagus', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '440', name: 'Artichoke', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '441', name: 'Leek', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '442', name: 'Shallots', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '443', name: 'Spring Onion', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '444', name: 'Bok Choy', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '445', name: 'Cantaloupe / Kharbuja', category: 'Food', status: 'Safe', reason: 'Wash skin before cutting (Listeria risk on rind).' },
  { id: '446', name: 'Muskmelon', category: 'Food', status: 'Safe', reason: 'Wash skin before cutting.' },
  { id: '447', name: 'Honeydew Melon', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '448', name: 'Peach', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '449', name: 'Plum', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '450', name: 'Nectarine', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '451', name: 'Cherry', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '452', name: 'Pear', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '453', name: 'Raspberry', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '454', name: 'Blackberry', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '455', name: 'Passion Fruit', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '456', name: 'Dragon Fruit', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '457', name: 'Persimmon', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '458', name: 'Star Fruit', category: 'Food', status: 'Caution', reason: 'Avoid if kidney issues.' },
  { id: '459', name: 'Durian', category: 'Food', status: 'Safe', reason: 'High sugar/fat. Moderate.' },
  { id: '460', name: 'Mangosteen', category: 'Food', status: 'Safe', reason: 'Safe.' },
  
  // Activities - Hobby
  { id: '461', name: 'Reading', category: 'Activity', status: 'Safe', reason: 'Relaxing.' },
  { id: '462', name: 'Painting / Drawing', category: 'Activity', status: 'Safe', reason: 'Relaxing. Use non-toxic paints.' },
  { id: '463', name: 'Pottery', category: 'Activity', status: 'Safe', reason: 'Safe.' },
  { id: '464', name: 'Meditation', category: 'Activity', status: 'Safe', reason: 'Highly recommended.' },
  { id: '465', name: 'Listening to Music', category: 'Activity', status: 'Safe', reason: 'Garbh Sanskar.' },
  { id: '466', name: 'Video Games', category: 'Activity', status: 'Safe', reason: 'Safe. Take breaks.' },
  { id: '467', name: 'Watching TV', category: 'Activity', status: 'Safe', reason: 'Safe.' },
  { id: '468', name: 'Cooking Classes', category: 'Activity', status: 'Safe', reason: 'Safe.' },
  { id: '469', name: 'Bowling', category: 'Activity', status: 'Caution', reason: 'Balance risk and heavy ball.' },
  { id: '470', name: 'Golf', category: 'Activity', status: 'Safe', reason: 'Safe.' },
  { id: '471', name: 'Tennis', category: 'Activity', status: 'Caution', reason: 'Risk of falling/sudden stops.' },
  { id: '472', name: 'Badminton', category: 'Activity', status: 'Caution', reason: 'Risk of falling.' },
  { id: '473', name: 'Table Tennis', category: 'Activity', status: 'Safe', reason: 'Low impact.' },
  { id: '474', name: 'Snorkeling', category: 'Activity', status: 'Safe', reason: 'Surface only. No diving.' },
  { id: '475', name: 'Surfing', category: 'Activity', status: 'Avoid', reason: 'Fall and impact risk.' },
  { id: '476', name: 'Ice Skating', category: 'Activity', status: 'Avoid', reason: 'Fall risk.' },
  { id: '477', name: 'Rollerblading', category: 'Activity', status: 'Avoid', reason: 'Fall risk.' },
  { id: '478', name: 'Skateboarding', category: 'Activity', status: 'Avoid', reason: 'Fall risk.' },
  { id: '479', name: 'Boxing', category: 'Activity', status: 'Avoid', reason: 'Abdominal trauma risk.' },
  { id: '480', name: 'Martial Arts', category: 'Activity', status: 'Avoid', reason: 'Fall/Impact risk.' },
  
  // Specific Indian Context
  { id: '481', name: 'Fasting (Karwa Chauth/Navratri)', category: 'Activity', status: 'Caution', reason: 'Dehydration/Hypoglycemia risk. Allow fruit/water.' },
  { id: '482', name: 'Wearing Mangalsutra/Bangles', category: 'Activity', status: 'Safe', reason: 'Safe. Watch for swelling (remove tight rings).' },
  { id: '483', name: 'Applying Bindi (Glue)', category: 'Beauty', status: 'Safe', reason: 'Safe.' },
  { id: '484', name: 'Using Sindoor', category: 'Beauty', status: 'Caution', reason: 'Some contain lead/mercury. Use herbal.' },
  { id: '485', name: 'Sitting Cross-legged', category: 'Activity', status: 'Safe', reason: 'Good for pelvis. Avoid if SPD pain.' },
  { id: '486', name: 'Sleeping on Floor', category: 'Activity', status: 'Safe', reason: 'Safe if comfortable. Getting up might be hard.' },
  { id: '487', name: 'Drinking Tap Water', category: 'Food', status: 'Avoid', reason: 'Boil or RO filter mandatory. Infection risk.' },
  { id: '488', name: 'Ice from Outside', category: 'Food', status: 'Avoid', reason: 'Often made from tap water.' },
  { id: '489', name: 'Chutneys (Raw)', category: 'Food', status: 'Caution', reason: 'Hygiene risk if restaurant made.' },
  { id: '490', name: 'Gola / Ice Lolly', category: 'Food', status: 'Avoid', reason: 'Water hygiene issues.' },
  { id: '491', name: 'Kulfi', category: 'Food', status: 'Safe', reason: 'Safe if branded/hygienic.' },
  { id: '492', name: 'Falooda', category: 'Food', status: 'Safe', reason: 'Safe. Watch sugar.' },
  { id: '493', name: 'Rabdi', category: 'Food', status: 'Safe', reason: 'Heavy but safe.' },
  { id: '494', name: 'Rasgulla', category: 'Food', status: 'Safe', reason: 'Safe protein sweet.' },
  { id: '495', name: 'Gulab Jamun', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '496', name: 'Barfi (Silver foil)', category: 'Food', status: 'Caution', reason: 'Ensure silver foil (Vark) is pure, not aluminum.' },
  { id: '497', name: 'Modak', category: 'Food', status: 'Safe', reason: 'Steamed is best.' },
  { id: '498', name: 'Puran Poli', category: 'Food', status: 'Safe', reason: 'Chana dal + Jaggery. Healthy.' },
  { id: '499', name: 'Thepla', category: 'Food', status: 'Safe', reason: 'Methi thepla is excellent.' },
  { id: '500', name: 'Khichdi', category: 'Food', status: 'Safe', reason: 'Best comfort food.' },
  { id: '501', name: 'Upma', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '502', name: 'Vada (Fried)', category: 'Food', status: 'Caution', reason: 'Acidity/Heartburn.' },
  { id: '503', name: 'Puri', category: 'Food', status: 'Caution', reason: 'Acidity/Heartburn.' },
  { id: '504', name: 'Bhatura', category: 'Food', status: 'Caution', reason: 'Acidity/Heartburn.' },
  { id: '505', name: 'Naan', category: 'Food', status: 'Safe', reason: 'Maida based. Eat in moderation.' },
  { id: '506', name: 'Roti / Chapati', category: 'Food', status: 'Safe', reason: 'Staple.' },
  { id: '507', name: 'Paratha', category: 'Food', status: 'Safe', reason: 'Stuffed parathas are nutritious.' }
];
