
import { SafetyItem } from './types';

export const SAFETY_ITEMS: SafetyItem[] = [
  // --- FOOD: SAFE ---
  { id: '1', name: 'Pasteurized Milk', category: 'Food', status: 'Safe', reason: 'Calcium is essential.' },
  { id: '2', name: 'Hard Cheeses (Cheddar/Parmesan)', category: 'Food', status: 'Safe', reason: 'Low moisture prevents bacteria.' },
  { id: '3', name: 'Yogurt / Curd', category: 'Food', status: 'Safe', reason: 'Excellent source of probiotics and calcium.' },
  { id: '4', name: 'Cooked Eggs', category: 'Food', status: 'Safe', reason: 'Whites and yolks must be firm to avoid Salmonella.' },
  { id: '5', name: 'Salmon', category: 'Food', status: 'Safe', reason: 'Low mercury, high Omega-3. Must be cooked.' },
  { id: '6', name: 'Shrimp / Prawns', category: 'Food', status: 'Safe', reason: 'Safe if fully cooked.' },
  { id: '7', name: 'Chicken (Cooked)', category: 'Food', status: 'Safe', reason: 'Safe. Ensure no pink meat remains.' },
  { id: '8', name: 'Ghee', category: 'Food', status: 'Safe', reason: 'Safe in moderation (Traditional calorie source).' },
  { id: '9', name: 'Saffron (Kesar)', category: 'Food', status: 'Safe', reason: 'Safe in small amounts (a few strands in milk).' },
  { id: '10', name: 'Coconut Water', category: 'Food', status: 'Safe', reason: 'Excellent for hydration and electrolytes.' },
  { id: '11', name: 'Spinach (Palak)', category: 'Food', status: 'Safe', reason: 'Wash thoroughly to remove soil bacteria.' },
  { id: '12', name: 'Almonds / Walnuts', category: 'Food', status: 'Safe', reason: 'Soaked almonds are easier to digest.' },
  { id: '13', name: 'Dates', category: 'Food', status: 'Safe', reason: 'High in iron. Don\'t overeat if you have GDM.' },
  { id: '14', name: 'Ginger', category: 'Food', status: 'Safe', reason: 'Great for morning sickness.' },
  { id: '15', name: 'Garlic', category: 'Food', status: 'Safe', reason: 'Good for immune system.' },
  { id: '16', name: 'Turmeric (Haldi)', category: 'Food', status: 'Safe', reason: 'Safe in normal food amounts.' },
  { id: '17', name: 'Cumin (Jeera) Water', category: 'Food', status: 'Safe', reason: 'Helps with bloating.' },
  { id: '18', name: 'Peanut Butter', category: 'Food', status: 'Safe', reason: 'Safe unless you are allergic.' },
  { id: '19', name: 'Oats', category: 'Food', status: 'Safe', reason: 'Good fiber for constipation.' },
  { id: '20', name: 'Tofu', category: 'Food', status: 'Safe', reason: 'Safe protein source.' },
  { id: '21', name: 'Mushrooms', category: 'Food', status: 'Safe', reason: 'Safe if cooked.' },
  { id: '22', name: 'Corn', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '23', name: 'Sweet Potato', category: 'Food', status: 'Safe', reason: 'High in Vitamin A (Beta-carotene form is safe).' },
  { id: '24', name: 'Apples', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '25', name: 'Bananas', category: 'Food', status: 'Safe', reason: 'Safe.' },
  { id: '26', name: 'Oranges', category: 'Food', status: 'Safe', reason: 'Vitamin C helps iron absorption.' },
  { id: '27', name: 'Ice Cream', category: 'Food', status: 'Safe', reason: 'Safe if made with pasteurized milk/eggs.' },
  { id: '28', name: 'Mayonnaise (Commercial)', category: 'Food', status: 'Safe', reason: 'Safe (uses pasteurized eggs).' },
  { id: '29', name: 'Chocolate', category: 'Food', status: 'Safe', reason: 'Safe in moderation (watch caffeine/sugar).' },
  { id: '30', name: 'Popcorn', category: 'Food', status: 'Safe', reason: 'Safe.' },

  // --- FOOD: CAUTION ---
  { id: '31', name: 'Caffeine', category: 'Food', status: 'Caution', reason: 'Limit to 200mg/day (approx 2 small cups).' },
  { id: '32', name: 'Tuna', category: 'Food', status: 'Caution', reason: 'Higher mercury. Max 1-2 times a week.' },
  { id: '33', name: 'Green Tea', category: 'Food', status: 'Caution', reason: 'Can affect folate absorption. Max 1-2 cups.' },
  { id: '34', name: 'Soda / Fizzy Drinks', category: 'Food', status: 'Caution', reason: 'Empty calories and high sugar.' },
  { id: '35', name: 'Spicy Food', category: 'Food', status: 'Caution', reason: 'Harmless to baby, but causes heartburn/acidity.' },
  { id: '36', name: 'Salt', category: 'Food', status: 'Caution', reason: 'Excess causes swelling/edema.' },
  { id: '37', name: 'Sugary Sweets', category: 'Food', status: 'Caution', reason: 'Risk of Gestational Diabetes.' },
  { id: '38', name: 'Pineapple', category: 'Food', status: 'Caution', reason: 'Contains bromelain. Safe in moderation, but traditionally avoided in excess.' },
  { id: '39', name: 'Grapes', category: 'Food', status: 'Caution', reason: 'Resveratrol in skin is debated. Wash thoroughly (pesticides).' },
  { id: '40', name: 'Herbal Teas', category: 'Food', status: 'Caution', reason: 'Chamomile/Peppermint usually safe; avoid unknown blends.' },
  { id: '41', name: 'Soy Sauce', category: 'Food', status: 'Caution', reason: 'Very high sodium.' },
  { id: '42', name: 'Street Food', category: 'Food', status: 'Caution', reason: 'High risk of hygiene-related infections (Typhoid/Gastro).' },
  { id: '43', name: 'Jaggery (Gud)', category: 'Food', status: 'Caution', reason: 'Healthy but high glycemic index.' },
  { id: '44', name: 'Fenugreek (Methi) Seeds', category: 'Food', status: 'Caution', reason: 'High doses can stimulate uterus. Food amounts are safe.' },
  { id: '45', name: 'Chinese Food (MSG)', category: 'Food', status: 'Caution', reason: 'MSG is generally safe but often causes headaches/bloating.' },

  // --- FOOD: AVOID ---
  { id: '46', name: 'Alcohol', category: 'Food', status: 'Avoid', reason: 'No known safe amount. Fetal Alcohol Syndrome risk.' },
  { id: '47', name: 'Raw Fish (Sushi)', category: 'Food', status: 'Avoid', reason: 'Parasite/Bacteria risk.' },
  { id: '48', name: 'Shark / Swordfish', category: 'Food', status: 'Avoid', reason: 'High Mercury content.' },
  { id: '49', name: 'Smoked Seafood', category: 'Food', status: 'Avoid', reason: 'Listeria risk unless cooked.' },
  { id: '50', name: 'Raw Oysters/Shellfish', category: 'Food', status: 'Avoid', reason: 'Vibrio bacteria risk.' },
  { id: '51', name: 'Raw/Runny Eggs', category: 'Food', status: 'Avoid', reason: 'Salmonella risk. (No homemade mayo/mousse).' },
  { id: '52', name: 'Unpasteurized Milk', category: 'Food', status: 'Avoid', reason: 'Listeria/E.coli risk.' },
  { id: '53', name: 'Soft Cheeses (Brie/Camembert)', category: 'Food', status: 'Avoid', reason: 'Listeria risk unless cooked steaming hot.' },
  { id: '54', name: 'Raw Meat (Steak Tartare)', category: 'Food', status: 'Avoid', reason: 'Toxoplasmosis risk.' },
  { id: '55', name: 'Deli Meats / Cold Cuts', category: 'Food', status: 'Avoid', reason: 'Listeria risk. Heat until steaming if you must eat.' },
  { id: '56', name: 'Pate / Meat Spreads', category: 'Food', status: 'Avoid', reason: 'Listeria risk.' },
  { id: '57', name: 'Liver', category: 'Food', status: 'Avoid', reason: 'Too much Vitamin A (Retinol) causes birth defects.' },
  { id: '58', name: 'Unripe Papaya', category: 'Food', status: 'Avoid', reason: 'Latex can trigger uterine contractions.' },
  { id: '59', name: 'Raw Sprouts', category: 'Food', status: 'Avoid', reason: 'E.coli/Salmonella risk inside the seeds.' },
  { id: '60', name: 'Unwashed Produce', category: 'Food', status: 'Avoid', reason: 'Toxoplasmosis risk from soil.' },
  { id: '61', name: 'Aloe Vera Juice', category: 'Food', status: 'Avoid', reason: 'Can cause uterine contractions/diarrhea.' },
  { id: '62', name: 'Energy Drinks', category: 'Food', status: 'Avoid', reason: 'Too much caffeine and stimulants.' },
  { id: '63', name: 'Ajinomoto (Excess)', category: 'Food', status: 'Avoid', reason: 'Avoid if sensitive.' },
  { id: '64', name: 'Sesame Seeds (Excess)', category: 'Food', status: 'Avoid', reason: 'Traditionally avoided in T1. Small amounts on buns are safe.' },
  { id: '65', name: 'Leftovers (>24 hours)', category: 'Food', status: 'Avoid', reason: 'Bacteria growth.' },

  // --- BEAUTY: SAFE ---
  { id: '66', name: 'Prenatal Massage', category: 'Beauty', status: 'Safe', reason: 'Safe with a trained therapist.' },
  { id: '67', name: 'Manicure / Pedicure', category: 'Beauty', status: 'Safe', reason: 'Ensure tools are sterilized.' },
  { id: '68', name: 'Hair Removal Creams', category: 'Beauty', status: 'Safe', reason: 'Use in well-ventilated area.' },
  { id: '69', name: 'Waxing / Threading', category: 'Beauty', status: 'Safe', reason: 'Skin may be more sensitive.' },
  { id: '70', name: 'Sunscreen (Mineral)', category: 'Beauty', status: 'Safe', reason: 'Zinc Oxide/Titanium Dioxide are best.' },
  { id: '71', name: 'Makeup', category: 'Beauty', status: 'Safe', reason: 'Safe.' },
  { id: '72', name: 'Baths (Warm)', category: 'Beauty', status: 'Safe', reason: 'Warm is safe. Hot is not.' },
  { id: '73', name: 'Sheet Masks', category: 'Beauty', status: 'Safe', reason: 'Safe.' },
  { id: '74', name: 'Glycolic Acid (<10%)', category: 'Beauty', status: 'Safe', reason: 'Safe in low concentrations.' },
  { id: '75', name: 'Vitamin C Serum', category: 'Beauty', status: 'Safe', reason: 'Good for pigmentation (melasma).' },
  { id: '76', name: 'Lactic Acid', category: 'Beauty', status: 'Safe', reason: 'Safe.' },
  { id: '77', name: 'Azelaic Acid', category: 'Beauty', status: 'Safe', reason: 'Good for acne.' },
  { id: '78', name: 'Benzoyl Peroxide', category: 'Beauty', status: 'Safe', reason: 'Safe in low concentrations (spot treat).' },
  { id: '79', name: 'Fake Tan (Creams)', category: 'Beauty', status: 'Safe', reason: 'Avoid sprays (inhalation risk).' },

  // --- BEAUTY: CAUTION ---
  { id: '80', name: 'Hair Dye', category: 'Beauty', status: 'Caution', reason: 'Wait until Trimester 2. Use ammonia-free.' },
  { id: '81', name: 'Salicylic Acid', category: 'Beauty', status: 'Caution', reason: 'Safe in low % (wash off), avoid high % peels.' },
  { id: '82', name: 'Essential Oils', category: 'Beauty', status: 'Caution', reason: 'Avoid in T1. Dilute heavily. (Avoid Sage, Rosemary, Jasmine).' },
  { id: '83', name: 'Sauna / Steam Room', category: 'Beauty', status: 'Caution', reason: 'Overheating is dangerous. Limit to <5 mins or avoid.' },
  { id: '84', name: 'Acupuncture', category: 'Beauty', status: 'Caution', reason: 'Ensure practitioner knows you are pregnant.' },

  // --- BEAUTY: AVOID ---
  { id: '85', name: 'Retinoids / Retinol', category: 'Beauty', status: 'Avoid', reason: 'Vitamin A derivatives cause birth defects.' },
  { id: '86', name: 'Isotretinoin (Accutane)', category: 'Beauty', status: 'Avoid', reason: 'Causes severe birth defects.' },
  { id: '87', name: 'Hydroquinone', category: 'Beauty', status: 'Avoid', reason: 'Absorption rate is high.' },
  { id: '88', name: 'Botox / Fillers', category: 'Beauty', status: 'Avoid', reason: 'Not enough safety data.' },
  { id: '89', name: 'Tanning Beds', category: 'Beauty', status: 'Avoid', reason: 'UV radiation and overheating.' },
  { id: '90', name: 'Hot Tubs', category: 'Beauty', status: 'Avoid', reason: 'Raises core body temperature too high (neural tube defects).' },
  { id: '91', name: 'Chemical Peels (Deep)', category: 'Beauty', status: 'Avoid', reason: 'Avoid.' },
  { id: '92', name: 'Laser Hair Removal', category: 'Beauty', status: 'Avoid', reason: 'Usually postponed until postpartum due to skin sensitivity.' },

  // --- ACTIVITY: SAFE ---
  { id: '93', name: 'Walking', category: 'Activity', status: 'Safe', reason: 'Best exercise.' },
  { id: '94', name: 'Swimming', category: 'Activity', status: 'Safe', reason: 'Relieves joint pressure.' },
  { id: '95', name: 'Prenatal Yoga', category: 'Activity', status: 'Safe', reason: 'Avoid lying on back after T1.' },
  { id: '96', name: 'Kegel Exercises', category: 'Activity', status: 'Safe', reason: 'Highly recommended.' },
  { id: '97', name: 'Sex', category: 'Activity', status: 'Safe', reason: 'Safe (unless doctor says "Pelvic Rest" or Placenta Previa).' },
  { id: '98', name: 'Driving', category: 'Activity', status: 'Safe', reason: 'Wear seatbelt below the belly.' },
  { id: '99', name: 'Flying', category: 'Activity', status: 'Safe', reason: 'Safe until 36 weeks (check airline). Walk every hour.' },
  { id: '100', name: 'Sleeping on Side', category: 'Activity', status: 'Safe', reason: 'Left side is best for blood flow.' },
  { id: '101', name: 'Computer Work', category: 'Activity', status: 'Safe', reason: 'Take eye breaks.' },
  { id: '102', name: 'Microwave Use', category: 'Activity', status: 'Safe', reason: 'Radiation does not leak.' },
  { id: '103', name: 'Metal Detectors', category: 'Activity', status: 'Safe', reason: 'Low frequency, safe.' },
  { id: '104', name: 'Dental Cleaning', category: 'Activity', status: 'Safe', reason: 'Inform dentist. Lidocaine is safe.' },
  { id: '105', name: 'Flu Shot', category: 'Activity', status: 'Safe', reason: 'Recommended.' },

  // --- ACTIVITY: CAUTION ---
  { id: '106', name: 'Running', category: 'Activity', status: 'Caution', reason: 'Safe if you were a runner before. Don\'t start new.' },
  { id: '107', name: 'Strength Training', category: 'Activity', status: 'Caution', reason: 'Lower weights, watch form.' },
  { id: '108', name: 'Cycling', category: 'Activity', status: 'Caution', reason: 'Balance issues as belly grows. Stationary bike is safer.' },
  { id: '109', name: 'Sleeping on Back', category: 'Activity', status: 'Caution', reason: 'Avoid after 20 weeks (compresses Vena Cava).' },
  { id: '110', name: 'Lifting Weights', category: 'Activity', status: 'Caution', reason: 'Avoid heavy lifting (>10kg).' },
  { id: '111', name: 'Hiking', category: 'Activity', status: 'Caution', reason: 'Avoid high altitude (>6000ft) if not acclimated.' },
  { id: '112', name: 'Painting', category: 'Activity', status: 'Caution', reason: 'Ensure good ventilation. Avoid oil-based paints.' },

  // --- ACTIVITY: AVOID ---
  { id: '113', name: 'Smoking', category: 'Activity', status: 'Avoid', reason: 'Causes low birth weight and preterm labor.' },
  { id: '114', name: 'Contact Sports', category: 'Activity', status: 'Avoid', reason: 'Trauma risk (Soccer, Basketball, Boxing).' },
  { id: '115', name: 'Horse Riding', category: 'Activity', status: 'Avoid', reason: 'High fall risk.' },
  { id: '116', name: 'Skiing / Snowboarding', category: 'Activity', status: 'Avoid', reason: 'Fall risk.' },
  { id: '117', name: 'Scuba Diving', category: 'Activity', status: 'Avoid', reason: 'Baby cannot decompress nitrogen bubbles.' },
  { id: '118', name: 'Hot Yoga (Bikram)', category: 'Activity', status: 'Avoid', reason: 'Overheating risk.' },
  { id: '119', name: 'Amusement Park Rides', category: 'Activity', status: 'Avoid', reason: 'G-force and sudden stops.' },
  { id: '120', name: 'X-Rays', category: 'Activity', status: 'Avoid', reason: 'Avoid unless emergency. (Shield belly if necessary).' },
  { id: '121', name: 'Changing Cat Litter', category: 'Activity', status: 'Avoid', reason: 'Toxoplasmosis risk.' },
  { id: '122', name: 'Cleaning with Bleach/Ammonia', category: 'Activity', status: 'Avoid', reason: 'Do not mix. Fumes are toxic.' },
  { id: '123', name: 'Insect Repellent (High DEET)', category: 'Activity', status: 'Avoid', reason: 'Use low concentration or natural.' },
  { id: '124', name: 'Hiking (High Altitude)', category: 'Activity', status: 'Avoid', reason: 'Avoid above 10,000ft. Oxygen levels drop.' },

  // --- HOUSEHOLD / HEALTH: SAFE ---
  { id: '125', name: 'Paracetamol', category: 'Household', status: 'Safe', reason: 'Safe for pain/fever.' },
  { id: '126', name: 'Tums (Calcium Carbonate)', category: 'Household', status: 'Safe', reason: 'Safe for heartburn.' },
  { id: '127', name: 'Saline Nasal Spray', category: 'Household', status: 'Safe', reason: 'Safe for colds.' },
  { id: '128', name: 'WiFi / Cell Phones', category: 'Household', status: 'Safe', reason: 'Non-ionizing radiation is safe.' },
  { id: '129', name: 'Gardening', category: 'Household', status: 'Safe', reason: 'Wear gloves due to soil bacteria.' },
  { id: '130', name: 'Paint (Latex)', category: 'Household', status: 'Safe', reason: 'Water-based is safe with ventilation.' },

  // --- HOUSEHOLD / HEALTH: AVOID ---
  { id: '131', name: 'Ibuprofen (Advil)', category: 'Household', status: 'Avoid', reason: 'Especially in T3 (Heart defects).' },
  { id: '132', name: 'Aspirin (High Dose)', category: 'Household', status: 'Avoid', reason: 'Bleeding risk.' },
  { id: '133', name: 'Naproxen', category: 'Household', status: 'Avoid', reason: 'NSAID.' },
  { id: '134', name: 'Pseudoephedrine', category: 'Household', status: 'Avoid', reason: 'Avoid in T1.' },
  { id: '135', name: 'Codeine', category: 'Household', status: 'Avoid', reason: 'Opioid.' },
  { id: '136', name: 'Lead Paint Dust', category: 'Household', status: 'Avoid', reason: 'Neurotoxic.' },
  { id: '137', name: 'Pesticides', category: 'Household', status: 'Avoid', reason: 'Avoid direct exposure.' },
  { id: '138', name: 'Passive Smoking', category: 'Household', status: 'Avoid', reason: 'Harmful.' }
];
